# Generated by Django 4.0.4 on 2022-05-28 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('tema_especifico', models.CharField(max_length=50)),
                ('consulta', models.TextField()),
                ('fecha_de_consuta', models.DateField(default=datetime.datetime(2022, 5, 27, 23, 53, 36, 677290))),
            ],
        ),
        migrations.DeleteModel(
            name='consulta',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_de_contacto',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 23, 53, 36, 718327)),
        ),
    ]
