# Generated by Django 4.0.4 on 2022-05-28 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foro', '0002_publicacion_delete_consulta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_de_consuta',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_de_publicacion',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 23, 59, 45, 845702)),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_de_contacto',
            field=models.DateField(default=datetime.datetime(2022, 5, 27, 23, 59, 45, 885739)),
        ),
    ]
