# Generated by Django 4.0.4 on 2022-06-19 22:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_foro', '0006_alter_contacto_fecha_de_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_de_contacto',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 19, 12, 50, 52141)),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_de_publicacion',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 19, 12, 50, 52141)),
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('publicacion_comentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_foro.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
